Update deps to fix owasp (#208)
* Update deps to fix owasp

* Fix  test

The OTP library in the test was no longer accepting the invalid secret
as a possible value
```
java.lang.IllegalArgumentException: Last encoded character (before the paddings if any) is a valid base 32 alphabet but not a possible value
```